[tools]
bun = "latest"
dotnet = "latest"
go = "latest"
java = "latest"
lazydocker = "latest"
lazygit = "latest"
lua = "latest"
node = "latest"
php = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
